name: build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build image
        run: docker build -t move-files .

      - name: test
        run: docker run -v $PWD/data:/data --name move-files move-files
